services:
  app:
    container_name: dexbooru-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${PORT}:5173"
    environment:
      - PORT=${PORT}
      - ORIGIN=${ORIGIN}
    depends_on:
      - postgres
      - redis
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: dexbooru-localstack
    restart: always
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:latest
    container_name: dexbooru-postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 5


  redis:
    image: redis:latest
    container_name: dexbooru-redis
    restart: always
    command: ["redis-server","--requirepass","${DB_REDIS_PASSWORD}"]
    ports:
      - "${DB_REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${DB_REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  localstack-data:
  pg-data:
  redis-data: